### ISSUE TITLE
Capitalize antipattern titles consistently

### ISSUE THREAD

**Issue by roryokane** [Linguistic-Antipatterns/linguistic-antipatterns.github.io#1]
The current short and long titles of the six antipatterns:

> - Confusable methods
>   - Multiple methods with confusably-similar names and effects
> - Inappropriately specific name
>   - Inappropriately-specific name
> - Incorrect associated spec
>   - Name is strongly associated with an inapplicable specification
> - Missing impled return type
>   - Missing implied return type
> - Name/Type Mismatch
>   - Name/Type Mismatch
> - Unexpected Side Effects
>   - Unexpected Side Effects

The last two are in title case, while the rest are in sentence case. The capitalization should be consistent.

I think sentence case everywhere will look better:

> - Name/type mismatch
>   - Name/type mismatch
> - Unexpected side effects
>   - Unexpected side effects

Since this issue is about editing the titles, I also wonder if the antipattern titles should always match their first headings. That question probably deserves its own issue, but I mention it in case seeing the titles quoted in this issue description inspires an easy fix for the inconsistency.

**Comment by jkoppel** [comment]
Good catch. I like it. Very meta.

> I also wonder if the antipattern titles should always match their first headings

For "confusable methods" and "incorrect associated spec," I do find the longer name in the heading helpful.

**Comment by note89** [comment]
Fixed now :)
