### ISSUE TITLE
This page uses 100% of one of my CPUs

### ISSUE THREAD

**Issue by valrus** [Linguistic-Antipatterns/linguistic-antipatterns.github.io#10]
Seems strange since it just displays text. I uploaded a quick profile from Firefox (the browser in which the page exhibited this behavior) in case that's of any use: https://share.firefox.dev/3dtF1oJ

**Comment by jkoppel** [comment]
<img width="1004" alt="Screen Shot 2022-08-16 at 9 37 36 PM" src="https://user-images.githubusercontent.com/1279592/185015501-0e520fde-a9d7-4a9f-b9fd-497635937020.png">

Replicated on Chrome. If my laptop wasn't so beefy, would have definitely bothered me befoer.

**Comment by note89** [comment]
Wow! okey, i'm gonna investigate this!

**Comment by jkoppel** [comment]
I believe this is fixed.
