### ISSUE TITLE
Missing CSS for inline links on iOS

### ISSUE THREAD

**Issue by pulustelu** [Linguistic-Antipatterns/linguistic-antipatterns.github.io#3]
Example of an indistinguishable link:
![E1F16EC2-B35F-4D1B-830A-16EB36DDA7A4](https://user-images.githubusercontent.com/35444188/184303669-53f83115-7afe-4837-b835-e24d53d5ee29.jpeg)
"this blog post" contains a link.

**Comment by note89** [comment]
Thank for the report!

I have added an explicit underline now, does it work better?

Checked with browser stack, and seems to be working

**Comment by note89** [comment]
Got one comment that this is fixed on reddit. 
https://www.reddit.com/r/programming/comments/wlx2wm/comment/ik06w7o/?context=3

**Comment by pulustelu** [comment]
Looks good to me
