### ISSUE TITLE
Desirable to have unique URLs per anti-pattern

### ISSUE THREAD

**Issue by jkoppel** [Linguistic-Antipatterns/linguistic-antipatterns.github.io#4]
As pointed out by commenter at https://www.reddit.com/r/programming/comments/wlx2wm/comment/ijytqqw/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by note89** [comment]
There now is a unique URL per antipattern. 
But I have not added some auto-scroll, which might be annoying or not.

Could try out opening the articles in modals, but space Is already limited. 
Of course, we could have a multipage site, I can try that out as well; just render the whole article alone with the antipatterns logo. Then users would just use the back button to go back.

**Comment by note89** [comment]
We got a "Thank you" and a gold award on Reddit from the commenter after the fix.
so I'm guessing it's satisfactory :)
